### ISSUE TITLE
разрешить в грамматике в качестве Statment'ов использовать Expression'ы?

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#10]
К примеру, почему нельзя использовать конструкцию
`a + b;` ?
Смысла в ней нет, но и ошибки тоже. Оптимизациями временная переменная, которой присвоится результат этого выражения, будет удалена как неиспользуемая. Однако в этом случае пропадет необходимость при реализации функций использовать два класса функций - функция-expr и функция-stat.

Какие мнения на этот счет? Хз, насколько это нам поможет, и будет ли вообще от этого выигрыш, но в голову идея пришла, и я решил ею поделиться)

**Comment by jknightguru** [comment]
В принципе, ничего плохого в этом нет. Займись :)

**Comment by jknightguru** [comment]
Надо, походу, прямой каст Expression -> Statement в грамматику добавить, и он будет один на все подобные юзкейсы.

**Comment by almikh** [comment]
Подождем - может, еще кто выскажется. Дело не горит...
