### ISSUE TITLE
Сделать пользовательский интерфейс для IL кода

### ISSUE THREAD

**Issue by TheVigor** [mmcsIT2015/OptimizedCompilersProject#100]

**Comment by TheVigor** [comment]
Посмотрите, пойдет? Там вроде что-то отображается.

**Comment by almikh** [comment]
Нормально. Вот какая просьба: 
Пусть панелька с IL-кодов отображается только для наших грамматик (когда они грузятся).
Когда грузится код PascalABC - есть там у нас такой пункт - пусть она скрывается.

Еще, если не в падлу, было бы неплохо сделать некоторое подобие... не помню как называется. Короче, чтоб ширину/высоту можно было мышкой поправить. Типа одно поле сделать уже, другое автоматически сделается шире... Взял за границу, потащил - и размеры бы менялись. Я правда хз, как это на шарпе делается.

**Comment by TheVigor** [comment]
Архитектор одобрил, задачу закрываем!
