### ISSUE TITLE
Тесты из Main.cs перенести в отдельный класс

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#101]
Реально в этом файле они лишние...

**Comment by unrealprox** [comment]
Вывел тесты в отдельный класс Testing

Теперь все свои тесты можете реализовывать в этом классе. Все тесты должны соответствовать делегатам Testing.CodeTest, либо Testing.RootTest.

Для тестирования нужно использовать функции Testing.PerformTests(), либо Testing.PerformAllTests()

Пример использования можно найти в Main.cs

Прошу ознакомиться, вывести эту информацию куда-нибудь, чтобы все видели, и закрыть Issue,

**Comment by valyaevanton** [comment]
Я вообще предлагаю оставить только пустую функцию main чтобы не приходилось каждый раз всё там комментировать и раскомментировать

**Comment by almikh** [comment]
Так и должно было быть, но все упорно заливают свои новые изменения в эту Main.

**Comment by unrealprox** [comment]
Если уже тут начали холивар, то я бы вообще сделал iCompiler библиотекой, а для консольного приложения сделал бы отдельный проект.

ПС. Заниматься этим я не буду!

**Comment by valyaevanton** [comment]
Лучше добавить Main.cs в gitignore и пусть каждый что хочет, то в нём и пишет.
П.С: Лёха, всё в твоих руках

**Comment by almikh** [comment]
Ничего в gitignore добавлять не нужно. Нужно просто не фиксировать этот файл, т.е. не добавлять его в коммит, и все. Как делаю я.

**Comment by almikh** [comment]
Надо бы внятные сообщения выдавать... имя файла, хотя бы, чтоль. А то как-то уныло все выглядит. kazanfar что-нибудь придумает.
