### ISSUE TITLE
Возможность открытия реального паскалевского кода (.pas)

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#102]
Реализовать в GUI подобную возможность. Пока с пустой функцией, в которую я смогу что-то вставить.

**Comment by almikh** [comment]
Желательно предусмотреть возможность показа панельки, в которой будет отображаться разность по времени между исходной программой, и оптимизированной.

**Comment by jknightguru** [comment]
Сделано полностью. Любые вопросы - сюда, либо по телефону. Типы там сам поменяешь, по желанию^^
