### ISSUE TITLE
Итерационный алгоритм - ошибочный?

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#103]
Нашел некоторые расхождения с книгой. Или это не расхождения... не забыть спросить на паре.

**Comment by PConst4** [comment]
То, что собирался спросить - спроси, а тест твой на бумаге на 4-й итерации стабилизировался, как надо.

**Comment by almikh** [comment]
Брали алгоритм из тетради, я надеюсь? Выходные результаты (In, Out) совпали с реализованным алгоритмом в коде?

**Comment by PConst4** [comment]
Из конспекта, откуда ж ещё? С программным не совпали, он [программный] чушь выдаёт.

**Comment by almikh** [comment]
Фотки решения в студию, пожалуйста. Буду разбираться.

**Comment by almikh** [comment]
Пробовали ваши результаты подсунуть в алгоритм с оптимизацией?
