### ISSUE TITLE
Сравнение содержимого контейнеров на C#

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#104]
Знает кто правильный способ? А то не хочу больше придумывать велосипеды...

**Comment by PConst4** [comment]
Метод Equals.

**Comment by jknightmmcs** [comment]
А оно есть у нас.

**Comment by jknightmmcs** [comment]
Block.cs, строка 134.

**Comment by jknightguru** [comment]
https://msdn.microsoft.com/library/bb348567(v=vs.100).aspx
