### ISSUE TITLE
Разобраться со сборкой

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#106]
В коммите 20de33d я попытался подключить один из наших подпроектов (PascalABC) в GUI. 
Сборка не сработала, ругается на отсутствующие ссылки и т.п. У меня нет времени разбираться с подобными моментами.

Нужно сделать так, чтобы закомментированный код (20de33d) в Forms.cs скомпилировался. Если что, можно посмотреть на проект PascalABC нашего Solution'на.

**Comment by almikh** [comment]
Заодно глянуть, почему релизная сборка не собирается.

**Comment by jknightguru** [comment]
Хорошо, посмотрю.

**Comment by jknightguru** [comment]
Конпелируется, но работает с ошибкой: SyntaxTreeChanger.Code == null
