### ISSUE TITLE
[GUI] Подсветкой синтаксиса никто не хочет заняться?

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#107]
Возможность набрать коммитов...
Да и вообще было бы круто.

**Comment by jknightguru** [comment]
Тогда бы уже допилить компилятор консольный, и сделать плагин к Eclipse, например. Т.к. наш гуй все равно в жизнь в качестве нормальной IDE смотреться не будет. 

P.S. Нет, я этим заниматься не хочу.

**Comment by unrealprox** [comment]
А я думаю нужно сделать плагин для Visual Studio! Уверен, наш архитектор с радостью займется этой задачей!

P.S. Нет, я этим заниматься не хочу.

**Comment by TheVigor** [comment]
А я бы хотел плагин под Android Studio. Заверните 2, пожалуйста.

P.S. Конечно же нет, я этим заниматься не хочу.

**Comment by almikh** [comment]
Я бы с радостью занялся написанием плагина к Атому, однако только в том случае, если бы все наши оптимизации (вроде областей и прочих) вами были бы уже написаны и работали. Но пока особого энтузиазма с вашей стороны по этому поводу я не наблюдаю.

Вы же помните, что инициатива имеет инициатора?) И учтите, я могу счесть сарказмом не первую часть ваших сообщений, а последнюю (которая после PS) - и назначить все озвученный варианты их авторам. А подсветкой синтаксиса в нашем GUI тогда заняться и сам, тем более, судя по этому примеру (http://www.cyberforum.ru/csharp-net/thread207266.html - он не совсем то, что нам нужно, но определенный ориентир) в этом нет ничего сложного.

> Т.к. наш гуй все равно в жизнь в качестве нормальной IDE смотреться не будет.

Естест-но, он ведь и не является нормальной IDE. Но элементарные улучшения ему не помешали бы.

**Comment by vladpy8** [comment]
"инициатива имеет инициатора"
- золотые слова, чувак

**Comment by almikh** [comment]
При прочих равных это относилось бы и ко мне. Сейчас это относится лишь к вашим инициативам)

**Comment by PConst4** [comment]
DoubleK займётся.

**Comment by almikh** [comment]
ну как там дела обстоят? Неужели задача оказалась настолько сложной?

**Comment by PConst4** [comment]
Нет, дело совсем в другом =) Скоро закрою.

**Comment by jknightguru** [comment]
Закрыто, т.к. проект сдан.
