### ISSUE TITLE
Компиляция и запуск IL-кода

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#109]
Там есть сейчас неактивная кнопка Скомпилировать (или что-то подобное).

Пусть в случае наличия сгенерированного IL-кода и клика по ней происходит компиляция этого кода и запускается отдельно скомпилированная программа. Предусмотреть возможность того, что по этой копке будет компилироваться не только IL-код (т.е. просто оставить место для еще одного условия.

Я **хочу** чтобы путь к компилятору (или как там эта штука называется) не был задан жестко. На крайний случай - пусть выдается сообщение об отсутствии его по стандартному пути и предложении ввести свой путь.

**Comment by unrealprox** [comment]
Сделал функцию компиляции IL-кода, которая возвращает путь к файлу программы (см. GUI.Form1.CompileILCode()

Написал пример использования для запуска скомпилированного приложения и отображения его вывода.

Нужно:
1. Добавить всякие проверки (наличие скомпилированного файла; возможности, указанные архитектором выше, т.к. я не понял, что он  имел ввиду)
2. Наверное, нужно сделать отдельное окошко для отображения вывода программы.
2.5. Лучше всего, наверное, сделать TabControl с различными вкладками (код, TA код, IL код, Вывод программы, Ошибки компиляции).

**Comment by almikh** [comment]
> т.к. я не понял, что он имел ввиду

Тем не менее, все сделано так, как я и хотел. Так что первый пункт можно считать выполненным.
