### ISSUE TITLE
Ввод ErrorList'а в генераторы трехадресного кода

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#110]
В трехадресном коде сделать ErrorList - вместо выбрасывания исключений (по крайней мере для семантических ошибок). С проверкой дублирования этих ошибок (т.е. завести класс для ошибки, и иметь возможность сравнивать эти классы). Это будет нужно для того, чтобы не бросать исключение при первом же косяке, а просто учесть эту ошибку и продолжить дальше. В самом конце можно будет либо бросить исключение (если список ошибок не пуст), либо вывести, к примеру, в лог.

**Comment by jknightguru** [comment]
Сделано.
