### ISSUE TITLE
Проблема с IL кодом

### ISSUE THREAD

**Issue by BatMich** [mmcsIT2015/OptimizedCompilersProject#112]
Вылетает исключение при вызове ILCodeGenerator.Generate(code) в функции RunParser  для теста "test-4.cn"
![err](https://cloud.githubusercontent.com/assets/14240377/11899946/a5a62a58-a5b3-11e5-98ca-8ba234afb98b.jpg)

**Comment by unrealprox** [comment]
Исправлено
