### ISSUE TITLE
DraggingConstantsOptimization не работает корректно

### ISSUE THREAD

**Issue by AndranikTukhikov** [mmcsIT2015/OptimizedCompilersProject#113]
Пока запускал всякие оптимизации и тестил их в интерфейсе столкнулся с проблемой.
DraggingConstantsOptimization вообще ничего не делает.
Да, я конечно понимаю, что это алгоритм который писал я сам.
НО я в нем теперь вообще ничего не узнаю...

![screenshot_1](https://cloud.githubusercontent.com/assets/14253787/11912067/a660f7a4-a63d-11e5-9a21-10a45b70d7a4.jpg)

**Comment by almikh** [comment]
Это хорошо, что какую-т ошибку ты нашел, но конкретно этот участок - всецело ваш)

**Comment by AndranikTukhikov** [comment]
Я просто хочу понять кто нассал ко мне в норку.

**Comment by AndranikTukhikov** [comment]
Проблема возникла при изменении в функции Optimize() Line.Operation на Line.BinExpr и дальнейших добавлений IsIdentity в CheckDragging. Как решать проблему не знаю т.к. не узнаю свой код.

**Comment by almikh** [comment]
Надо разбираться) Время еще есть, вперед! На крайний случай можно переписать, благо кода не много.

**Comment by AndranikTukhikov** [comment]
Опытным путем было выяснено, что GetAliveVariables работает немного странно для объявлений переменных:
![image](https://cloud.githubusercontent.com/assets/14253787/11913704/678e9a04-a67e-11e5-813f-b3df41f88712.png)
или это нормально?

**Comment by almikh** [comment]
Кто занимался этими `живыми переменными`? Отзовись.

**Comment by TheVigor** [comment]
Есть подозрение, что человек, написавший GetAliveVariables, как-то связан с клопой, блинк даггером и миной.

**Comment by AndranikTukhikov** [comment]
В общем жду ответа.

**Comment by AndranikTukhikov** [comment]
Гоша не появился?

**Comment by jknightguru** [comment]
Появился, посмотрю завтра. Сегодня, точнее.

**Comment by jknightguru** [comment]
Живые переменные сделаны. Еще, товарищи. Когда лезем от начала до конца перерабатывать чужой код, думаем, что делать, хорошо?

Т.к. мой код не зависел от Line.<CLASS_NAME>, и эта возможность(когда не BinaryExpr, а Identity по сути) была реализована, но потом кто-то с умными руками все переделал, и я уже к этому коду третий раз возвращаюсь - что-то отваливается.

Одно херово - история файла обвалилась, искать по всему репозитарию - откровенный геморрой.

https://github.com/mmcsIT2015/OptimizedCompilersProject/commit/e3a10fb98098a99ff5e03504699abddb90949188

Вот вам коммит, в котором я добавлял эти долбаные проверки. Если посмотреть внимательно, то коду было совершенно насрать на то, сколько там справа определено - одна или две переменных. Он просто работал. Но тут кому-то захотелось избавиться от класса Line нахрен, и понаписать болота, в котором без поллитра не разобраться. 

Сейчас вместо того, чтобы быстро пофиксить проблему, я блядь полчаса бегал по коду в поисках того, чтобы понять, что же блядь за класс у этого говна (s = c). А обратную совместимость со старым кодом нельзя было оставить? У нас кроме интерфейсов еще и наследование есть, кстати... Ах да, там же виртуальные функции с оверрайдом, охуеть, етож первый курс вспоминать придется!

Бомбит, товарищи. А тому, кто переделывал мой код на собственный лад, сапог бомжа в огород. Для чего Issues в репозитарии созданы? Можно было бы и мне это предложить.

**Comment by jknightguru** [comment]
Не удивлюсь, если что-нибудь еще отвалится. Я за этот код ручаться отказываюсь.

**Comment by jknightguru** [comment]
Игорь, была бы шутка уместна, если бы это гомно писал я. Но, тут порефакторили...

**Comment by TheVigor** [comment]
Та, её никто не понял, так что забей. Тебя Андрюша весь день ждал, пытались тебя призвать.

**Comment by jknightguru** [comment]
Гхм, попробуйте задачу присвоить пораньше. Я на весь этот флуд отовсюду не подписан. Кстати, пусть теперь тот человек, который этим занимался, UnaryExpr в обработку добавит: ее там тоже нет. Сам - не буду. Из плохого настроения.

**Comment by jknightguru** [comment]
Только сейчас в голову пришло, что у нас там в Line сущностей поприбавилось.

**Comment by jknightguru** [comment]
Кстати, S = c - Identity, а == что?

**Comment by unrealprox** [comment]
> Кстати, S = c - Identity, а == что?

a == - это BinaryExpr с типом Operation.Equal, на сколько я помню

**Comment by almikh** [comment]
> я <..> полчаса бегал по коду в поисках того, чтобы понять, что же <..> за класс у этого говна

Я бывает и по полтора часа сижу, разбираюсь со всем говном, которое тут понаписали, и почему это говно не работает. Будь моя воля и свободное время, я бы все сам написал - но это запрещено, так что бегаем по коду молча.

> в котором без поллитра не разобраться

Зато если разобраться, все становится (на мой взгляд) более понятно.

> А обратную совместимость со старым кодом нельзя было оставить

В данном случае это было невозможно. Да и насколько это было необходимо? С того момента прошло почти 2 месяца - уже давно можно было самому проверить все и в случае необходимости исправить.

> У нас кроме интерфейсов еще и наследование есть, кстати... Ах да, там же виртуальные функции с оверрайдом, охуеть, етож первый курс вспоминать придется!

В данном контексте это не соответствует действительности.
Я, кстати, рассказывал на паре обо всех произведенных с Line изменениях - ты просто тогда пропустил как раз. Так что...

> Сам - не буду

Будешь) Возьмешь, и добавишь - задач у тебя осталось не так много (а если и есть - то мелкие). Вместо того, чтобы писать такую простыню текста, уже давно бы взял и добавил)

> Я на весь этот флуд отовсюду не подписан

А зря. Мб, и не возникло бы такой ситуации, будь ты раньше информирован о изменениях.

**Comment by jknightguru** [comment]
Методы этих классов можно было обозвать как угодно, сделав в них обработку исходных полей класса Line. Так что не надо рассказывать о том, насколько невозможно это сделать. Сейчас бы ничего там не изменилось. 

Менять код полностью без согласования с его автором в надежде, что все всегда будет работать хорошо, плохая идея, не правда ли? 

Вижу, там Expr от Line наследуется. Извиняюсь, не заметил сразу. Что, кстати, неправильное именование, т.к. Expression - это лишь правые части, а вместе с левой это Statement.

Понятнее стало, говоришь? Раньше было рабочее утверждение: переменная в некотором виде объявляется в left, используется в first, second, не важно, в каком виде. И это работало для _всех_ возможных вариаций строки трехадресного кода! Теперь у нас этот метод разросся в небеса, потому что есть отдельный кусок для BinaryExpr, отдельный - для UnaryExpr, отдельный - для Identity, отдельный - для ConditionalJump, FunctionParam, bla, bla, bla. Ну, ты понел. А если появится еще сущность - ее снова нужно будет добавить, потому, что метод не способен с новыми элементами работать! 

Итог: масштабируемость - нулевая, модифицируемость - нулевая, и даже понятность соснула, ибо  раньше там был десяток строк с простым инвариантом, описанным выше, а теперь там куева гора кода, причем каждый класс работает по-своему, и еще сиди, смотри, где там что лежит в них, а для начала - еще и определи, что же там за строка в трехадресном коде! Хорошо хоть, в .NET есть GetType() - ато я б сдох визиторы разбирать. Однообразности - ноль.

**Comment by jknightguru** [comment]
Добавил уже... Не хочется, чтобы опять потом пришлось что-то фиксить, когда в меня снова сапогом кинут.

**Comment by jknightguru** [comment]
Как надо было сделать: 

http://pastebin.com/YtHgXjwZ
И весь старый код неожиданно жив!!! =3

**Comment by almikh** [comment]
Я не говорю, что это сделать невозможно. Я говорю, что это нецелесообразно. Потому что все три (или 4?) поля нужны только для бинарного выражения, для остальных хватает одного-двух. А то и вообще без них обходятся. Т.е. это нехилое количество лишней памяти.

> Что, кстати, неправильное именование, т.к. Expression - это лишь правые части, а вместе с левой это Statement.

Согласен, тут мой косяк. Об этом не подумал. По-хорошему, там и не BinaryExpr надо, а BinaryStatment, да и с унарным похожая ситуация, ну да ладно. В самом конце может поменяю, если не забуду.

> А если появится еще сущность - ее снова нужно будет добавить, потому, что метод не способен с новыми элементами работать. Итог: масштабируемость - нулевая, модифицируемость - нулевая <..>

Ну да, у этого масштабируемость просто божественна:

``` cs
switch(this[i].command)
{
   case "goto":                        
     break;
   case "call":
     break;
   case "param":
   ...
```

=)

**Comment by jknightguru** [comment]
Их таких четыре штуки, и новые бы не появились. И эти были исключительно из-за ошибки проектирования: зачем было для if, call, param, и прочее в left пихать? Это, опять таки, не я писал. Если бы параметры к if, param были бы унифицированы(не объявляется там ничего, значит - относится сугубо к выражениям, пихаем в first/second), то отдельные куски для них были бы не нужны.

**Comment by jknightguru** [comment]
Было бы только goto -> break и call -> break, т.к. мы там реально к переменным не обращаемся.

А про лишнюю память... Пожалуйста, только не в эту сторону. Сколько должно быть переменных, чтобы ими хотя бы килобайт памяти забить? Если ответишь на этот вопрос "мало" - приходи, аргументируй. Я не верю. Бегать за памятью надо в ограниченном пространстве, если пишем реалтайм систему под ардуино, а не когда мы пишем компилятор, который работает один раз, и один черт всю эту память выделяем(т.к. страничная адресация заставляет как минимум одну страницу(4 кб) под каждый new выделять. Эт так, для новостей.

**Comment by AndranikTukhikov** [comment]
Спасибо все подправил. Все работает. Проблема закрыта.
