### ISSUE TITLE
ActiveVarsOptimization работает не верно.

### ISSUE THREAD

**Issue by AndranikTukhikov** [mmcsIT2015/OptimizedCompilersProject#115]
До оптимизации:
![image](https://cloud.githubusercontent.com/assets/14253787/11913503/bc1bee58-a676-11e5-9a7b-01a11c8bec64.png)

Первое применение:
![image](https://cloud.githubusercontent.com/assets/14253787/11913507/ec2595f4-a676-11e5-986b-f4d93180c2d3.png)

Второе применение:
![image](https://cloud.githubusercontent.com/assets/14253787/11913511/0e51fc76-a677-11e5-91ce-acdd22b79911.png)

**Comment by almikh** [comment]
Подправил этот (и не только) алгоритм в коммите dc08f3c. Просьба проверить еще раз.

**Comment by AndranikTukhikov** [comment]
![image](https://cloud.githubusercontent.com/assets/14253787/11913912/a3c7ae24-a684-11e5-88d4-1aaf46fa4710.png)
нууу я нажал Optimize и ничего не произошло... Это так и должно работать?
Если да, то закрываем)

**Comment by AndranikTukhikov** [comment]
Это:
![image](https://cloud.githubusercontent.com/assets/14253787/11913927/1282c164-a685-11e5-82de-779469a4e904.png)
Превратилось в это:
![image](https://cloud.githubusercontent.com/assets/14253787/11913938/46669730-a685-11e5-98d6-5b4d0a72be9e.png)

**Comment by almikh** [comment]
Ну, формально это правильно.
Эти переменные нигде ведь не используются. Если бы после if'а они использовались где-нибудь - другое дело, их бы оставило. А так...

**Comment by almikh** [comment]
> и ничего не произошло

Так ничего и не должно было произойти. Это ведь один единственный блок, тут только DCE работает. А ему делать нечего.

**Comment by AndranikTukhikov** [comment]
Значит закрываем, если проблема решена.
