### ISSUE TITLE
{ int a = 2 + 2; cout << a; } не работает. { int a = 2; cout << a; } - работает.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#116]
Собственно, сабж. Разобраться, пожалуйста. 

P.S. Были небольшие изменения с VarDeclListNode, прошу посмотреть визиторы, возможно, я сломал. Но маловероятно - я не туда лазил.

**Comment by jknightguru** [comment]
Нет, не я сломал. Ибо трехадресный код - корректный.

**Comment by jknightguru** [comment]
И в таблице имен все хорошо.

**Comment by almikh** [comment]
Хмм... У меня работает. Ты типа пофиксил это, или как?

**Comment by almikh** [comment]
Заодно пофиксил баг с проверкой переменной на необъявленность...

**Comment by jknightguru** [comment]
Нет, ничего я не фиксил... Странно себя ведет. Вылетает с эксепшеном скомпилированное приложение - сейчас посмотрел. Причем, вылетает Фреймворк - типо, неправильный модуль. Посмотрел сейчас на скомпиленный IL-код - вроде все норм. Такое поведение только для объявлений вида int k = <Int> <op> <Int>(без переменных).
