### ISSUE TITLE
Учет в def-use доп. строк

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#118]
В частности, в use нужно учитывать строки FunctionParam и ConditionalJump

**Comment by jknightguru** [comment]
Гхм. У нас разные Def-Use?..=3 Я ж вроде пофиксил.

**Comment by almikh** [comment]
А, ну тогда пардон. Я думал, по-прежнему две разные реализации) Сами решите, кому этим заняться(я о def-use).

**Comment by TheVigor** [comment]
У нас по-прежнему два def-use, и меня немного напрягает, что мы делаем одно и тоже. Когда я смотрел Георгия реализацию я так и не увидел, чтобы для каждого блока возвращалось что-то вида pair(DEF, USE), там просто хэш-сет строк. Как из него выудить дефы и юзы ?

Представление вида pair(DEF,USE) нужно для алгоритма анализа активных переменных.

Фактически у тебя там только правые части, то есть юзы. А еще нужны левые для дефов. И их надо как-то разделять. Разве нет?

**Comment by almikh** [comment]
Тут можно только смириться, пусть остается как есть) Типа, у нас разные def-use используются для разных целей)

Так что задача актуальна)

**Comment by jknightguru** [comment]
У меня оно не для разных блоков работает, только в пределах блока. Так что у нас они реально разные.

**Comment by TheVigor** [comment]
Ок.

**Comment by TheVigor** [comment]
Done
