### ISSUE TITLE
def-use, gen-kill

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#119]
В частности, в use нужно учитывать строки FunctionParam и ConditionalJump.
В kill я не помню что, но тоже нужно для этих строк учесть.

**Comment by jknightguru** [comment]
В Def-Use они есть оба. Сейчас посмотрю Gen-Kill.

**Comment by jknightguru** [comment]
Gen FunctionParam не использует, равно как и ConditionalJump.

Kill - пересечение множеств Gen между блоками, ему плевать на строки. Соответственно, все ок.
