### ISSUE TITLE
Просмотреть все оптимизации

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#121]
Каждый автор оптимизации должен просмотреть свою работу и выяснить, не упустил ди он где момент, когда может потеряться метка.

В частности, это может быть при удалении строки или замене этой строки другой (В ConstantFolding я поправил). При удалении строки  с меткой стоит ее заменять на EmptyStatement(), которому присвоить теряющуюся метку.

Жду, что сегодня-завтра сюда отпишутся все, к этому вопросу причастные.

**Comment by unrealprox** [comment]
Оптимизация общих подвыражений:
Ошибок не обнаружил: У нас оптимизация выполняется в пределах базового блока. Как я понял, все, что имеет метки, делит код на блоки. Т.е. метка может быть только у первой строки блока. А наш алгоритм первую строку ну ни в каком случае не будет обновлять.

**Comment by almikh** [comment]
А всем остальным плевать... ну ок.
