### ISSUE TITLE
Обновление области IL-кода при ошибках и более информативные сообщения об ошибках

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#123]
![image](https://cloud.githubusercontent.com/assets/4621400/11958586/b4e99530-a8d9-11e5-8fd6-208561528e6b.png)

**Comment by unrealprox** [comment]
Была ошибка в точке запятой в конце if-else )))))

Но сообщение не информативно!

И область все равно не обновляется

**Comment by almikh** [comment]
Ну, я не о таких сообщениях вел речь. Это уже косяк не в грамматике, а в коде у кого-то.
Стоило бы проверить. Займись как раз, все равно больше делать нечего.

**Comment by unrealprox** [comment]
Я уже устал разбираться в чужом коде. Пусть хозяева разбираются.

**Comment by almikh** [comment]
А я вот не устал, слушай. 

Тем более тут можно было бы найти, у кого косяк, и на него спихнуть. Я этим точно заниматься не буду.

**Comment by almikh** [comment]
Виновата точка с запятой за предпоследней закрывающей скобкой.

**Comment by unrealprox** [comment]
> Была ошибка в точке запятой в конце if-else )))))
> 
> Виновата точка с запятой за предпоследней закрывающей скобкой.

Спасибо, Кэп!

> Но сообщение не информативно!
> И область все равно не обновляется

Только вот смысл issue был в другом

**Comment by almikh** [comment]
Теперь таких сообщений не будет. По крайней мере, в этом случае.
А все возможные исключения я предусмотреть не могу.

А с областью и сам бы поковырялся.
