### ISSUE TITLE
Косяк в DraggingConstantsOptimization

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#125]
В коммите a0e18b2 я закомментировал одну строку, которая в определенных ситуациях приводила к зацикливанию.

Хочу услышать объяснения - чем руководствовался автор, когда эту строку писал? Т.е. не удалил ли я чего лишнего?

**Comment by AndranikTukhikov** [comment]
Гляну завтра вечерком и отпишусь.
Я еще кое-что планировал туда добавить.

**Comment by almikh** [comment]
Если что, именно пример a.pas в случае применения нового Мишиного алгоритма ложит DraggingConstantsOptimization. Т.е., зацикливается. Ложил, до исправления. КОнкретно, вот тут:

```
                        else if (variable.Equals(iLine.second))
                        {
                            NumberOfChanges += 1;
                            iLine.second = const_value;
                        }
```

iLine.second и const_value были одинаковые, и происходила бесконечная замена.

**Comment by AndranikTukhikov** [comment]
Понял-понял) спасибо за наводку)

**Comment by AndranikTukhikov** [comment]
я там порядок навел только что
