### ISSUE TITLE
ConstantsPropagationOptimization - слишком рьяно выполняет свою работу

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#126]
Пример, когда тут протягивать константное значение i не нужно.

```
    int i = 0;
    while (i == 0) {
        i = i + 1;
    }
```

А оно протягивается, и получается (если перевести в программу)

```
    while (0 == 0) {
        i = 1;
    }
```

Возможно, придется править ConstantFolding или DraggingConstantsOptimization.
Нужно выяснить, в каком именно месте это происходит. Или просто в уже новом алгоритме не 'подавать эту переменную для протягиваться' - это было бы предпочтительнее.

Можно позвонить мне, обсудим.

**Comment by BatMich** [comment]
Да, ошибка, действительно, имеется. В лоб решить не получилось - переделаю позже.

**Comment by BatMich** [comment]
Поправил. Чуть позже будет документация
