### ISSUE TITLE
Ошибка в генерации il-кода

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#129]
А точнее, в его компиляции.
Компиляцию ложит программа вида

```
int a, b, c, d;
a = b + c;
if (1) {
    d = b + c;
}
```

Опытным путем выяснил, что дело в `if (1) {`.
Наверное, стоит все ненулевые числа в условиях при генерации IL кода преобразовывать в true, а ноль - в false. Принудительно.

Еще было бы неплохо добавить сравнение времени выполнения оптимизированного и неоптимизированного IL-кода (по примеру в ProcessPascalABCNETCode) - но это уже смотреть по времени. Если успеете - хорошо, нет - ну, на нет и суда нет.

**Comment by jknightguru** [comment]
Тут стоит добавить наверное, что float в принципе нельзя преобразовывать в логическое значение - ошибка генерации кода, и все тут. Ато if (0.00000000000000071) будет как-нибудь.

**Comment by unrealprox** [comment]
Я исправил код, но теперь ошибка появляется из-за того, что 1 содержится в списке переменных, что как мне кажется быть не должно

![image](https://cloud.githubusercontent.com/assets/4621400/11997024/2260e498-aa82-11e5-8e30-9b95c97e5eed.png)

**Comment by almikh** [comment]
Этого действительно быть не должно, спасибо.

**Comment by almikh** [comment]
> что float в принципе нельзя преобразовывать в логическое значение

Пусть будет, мы наш компилятор для инженерных расчетов использовать не будем)

Косяки исправлены, все работает. Благодарю за оперативность.
