### ISSUE TITLE
Не хватает разделов документации!!!

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#132]
1. Pascal-подобная грамматика (DoubleK)
2. ББ/Устранение мертвого кода (DoubleK)

Итерационные алг
3. /активные переменные/оптимизации (DoubleK)
4. Распространение констант (Ultimate) (Дописывают)

Анализ графа для областей
5. Определить обратные ребра в CFG (DoubleK)
6. Приводимость графа (DoubleK)

**Comment by chekist131** [comment]
5, 6 (DoubleK)

**Comment by chekist131** [comment]
DoubleK будут дописывать документацию на паре
