### ISSUE TITLE
Написать обобщенный граф, и от него унаследовать наш.

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#17]

**Comment by valyaevanton** [comment]
Класс CFG. Когда заменишь все использования - удали старый граф, и из BaseBlockPartition тоже

**Comment by valyaevanton** [comment]
Потом может быть напишу обобщенный граф, но смысла в нём не вижу

**Comment by almikh** [comment]
Короче, задачу можно считать решенной.

**Comment by valyaevanton** [comment]
Любишь ты всё переименовывать)
