### ISSUE TITLE
Добавить унарную операцию. Почему ее, собственно, до сих пор нет?

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#19]

**Comment by almikh** [comment]
В грамматику ее вроде добавили, осталось для нее генерацию трехадресного кода реализовать.

**Comment by unrealprox** [comment]
Я бы советовал сразу все изменения в грамматику внести, пока слишком много переделывать не пришлось (я к примеру говорю об объявлении переменных)

**Comment by almikh** [comment]
Изменил грамматику (было сделано не совсем то, что я имел ввиду), добавил генерацию кода.

Если есть желание, можно в некоторые оптимизации добавить и учет `UnaryExpr` - так теперь называется строка кода для унарного оператора. `Operation` переименована в `BinaryExpr`.

**Comment by unrealprox** [comment]
Компилятор неправильно обрабатывает унарные операции, зачем-то создавая дополнительные переменные
![image](https://cloud.githubusercontent.com/assets/4621400/11280209/d9a184e8-8f05-11e5-81d2-2811ec317c6f.png)

ПС. Доделал оптимизацию "Устранение общих подвыражением" с учетом унарных операций

**Comment by almikh** [comment]
Сделал генерацию как в остальных конструкциях, и поплатился... 
Можно, конечно, поправить, но тогда код генерации усложнится - нужно будет проверять, переменная ли с этой унарной операцией или другое выражение, к примеру `a = -(b + c)`.

Мне это делать лень. Если найдется желающий - пожалуйста, я только за.

Оставим это на работу оптимизаций.

**Comment by unrealprox** [comment]
А еще неправильно поставлен приоритет для унарной операции
![image](https://cloud.githubusercontent.com/assets/4621400/11280275/53cb2a8a-8f06-11e5-8b61-c0584db88029.png)

**Comment by almikh** [comment]
А вот это действительно косяк.

**Comment by unrealprox** [comment]
> Мне это делать лень. Если найдется желающий - пожалуйста, я только за.

А мне вот было не лень допиливать оптимизацию для унарных операцией (новый класс создавать, функцию, хитрости обходить, т.к. у нас тождество это бинарная операция с типом None - извращение!!!!!)

Так что, потрудитесь пожалуйста исправиться
Заодно, я бы попросил, чтобы тождество все-таки было отдельным классом, а не бинарной операцией

**Comment by almikh** [comment]
ну, раз такое дело, тогда конечно)

PS
Среди унарных операций есть операция "`!`".
Если "`-`" еще можно было туда (в бинарную) при желании засунуть, то это - нет.
Если есть предложения по тому, как элегантно обыграть эту ситуация (с тождеством, унарными операциями и т.п.) - милости прошу, весь внимание.

**Comment by unrealprox** [comment]
> Если есть предложения по тому, как элегантно обыграть эту ситуация (с тождеством, унарными операциями и т.п.) - милости прошу, весь внимание.

http://ru.cppreference.com/w/cpp/language/operator_precedence

Как делать приоритеты в грамматике, Станислав Станиславович рассказывал

**Comment by almikh** [comment]
Про это я в курсе. Я имею ввиду 

> у нас тождество это бинарная операция с типом None - извращение!!!!!

**Comment by unrealprox** [comment]
Кто занимался парсингом выражений пусть допилит ) Что тут сложного?

**Comment by almikh** [comment]
С другой стороны, класс для унарной операции есть, почему не быть классу и для тождества...

**Comment by unrealprox** [comment]
Так было бы красивее, раз уже итак весь код переделали под красоту

**Comment by almikh** [comment]
Что-то в этом есть.

**Comment by kazanfar** [comment]
Это по ходу косяк нашей команды. Если Алексей позволит, мы можем заняться допиливанием .yacc и .lex файлов

**Comment by almikh** [comment]
Я уже все исправил, все норм теперь.

**Comment by almikh** [comment]
Лучше добавьте у себя, в Pascal.lex, возможность пользоваться табами... там символ `\t`  вставить в одно место нужно лишь, глянь, как это сделано в С-грамматике.

**Comment by kazanfar** [comment]
Ок
