### ISSUE TITLE
Последний коммит не компилируется.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#22]
Согласно правилам работы с репозитариями такой беды происходить не должно.

Ребят, давайте уже так: не компилируется -> не коммитим. Серьезно...

**Comment by almikh** [comment]
Какой-то нехороший человек убрал из настроек компиляцию проекта GUI.
Да еще и платформу зачем-то поменял  (а учитывая, кто это GUI делал, ясно, кого пинать =)).

Я по началу думал на свою студию, скомпилировать принудительно ведь у меня получилось, но после этого сообщения полез и убедился, что дело в файле проекта.

Проверь-ка после коммита ab3ac408614d, последнего.

**Comment by jknightguru** [comment]
Компиляция SimpleLang удалась, с компиляцией гуя не случилось:

---

Error       Invalid Resx file. Could not find file '...\OptimizedCompilersProject\GUI\Resources\run.png'. 
...\OptimizedCompilersProject\GUI\Properties\Resources.resx

**Comment by almikh** [comment]
Черт возьми, забыл прикрепить... Моя промашка.
Повтори.
