### ISSUE TITLE
Баги гуйцов.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#23]
1. При нескольких запусках кнопки Start счетчик сгенерированных переменных (@t) не обнуляется.
2. Редактор в зависимости от кодировки порой не видит переносы строк: { a = 4 + f(4, g(6, 7, 8));}
3. Выбор между грамматиками заблокирован.

Предложение - по поводу 3.:
1. Создать два файла SimpleYaccС.cs, SimpleYaccPascal.cs. Думаю, в генерации там где-нибудь имя выходного файла задать можно.
2. При чтении файла по расширению(дропнуть .txt, использовать другие расширения) понять, какая ожидается грамматика, и создать дерево, используя нужный код-генератор. Затем работа прежняя, как и раньше.

**Comment by jknightguru** [comment]
MessageBox.Show("Error: Could not read file from disk. Original error: " + ex.Message);
MessageBox.Show("Файл не найден");
MessageBox.Show("Лексическая ошибка. " + ee.Message);

-новый файл
-Start

Может, стоит с языком определиться?

**Comment by almikh** [comment]
Пока не реализовано несколько грамматик - по этому поводу даже задача есть. Было решено в скрипте генерировать сразу обе грамматики, в два разных файла, и оба эти файла (как ты заметил - с разными названиями) подключать в проект. 

Можно еще запариться и написать обертку, которая внутри себя будет вызывать и парсер, и сканер для нужной грамматики - а наружу выдавать лишь дерево.

Я собирался ее сделать завтра.
Если есть желание - возьми ее на себя и вперед, я займусь другими вещами. Сделать это нужно, опять же, завтра к вечеру.

**Comment by almikh** [comment]
Язык - английский. Я, видать, не все нашел. Исправляй сразу. В сообщениях русский язык в принципе еще ладно, но вот в названиях переменных...

**Comment by jknightguru** [comment]
Сделаю утром обертку.

**Comment by jknightguru** [comment]
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

using System.IO;

using SimpleCompiler;
using SimpleScanner;
using SimpleParser;
using SimpleLang;

Кому было скучно? =3

**Comment by jknightguru** [comment]
Улетел большой-большой коммит.

**Comment by jknightguru** [comment]
Лол, такой большой, что сервер ошибку выдал. Секундочку..

**Comment by jknightguru** [comment]
С наскоку отказывается... В общем, завтра разберусь.

**Comment by almikh** [comment]
Судя по `using System.Windows.Forms;`, можно догадаться, кому)

**Comment by valyaevanton** [comment]
Лёха, счётчик сгенерированных переменных обнуляй сам. Я боюсь что-то менять у тебя)

**Comment by almikh** [comment]
Ограничением на количество символов в поле ввода займешься в рамках этой задачи?) или новую создавать?)

**Comment by valyaevanton** [comment]
Не надо новую)

**Comment by valyaevanton** [comment]
Готово
