### ISSUE TITLE
Обертка для грамматик.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#24]
---

Можно еще запариться и написать обертку, которая внутри себя будет вызывать и парсер, и сканер для нужной грамматики - а наружу выдавать лишь дерево.

---

**Comment by jknightguru** [comment]
Пришлю коммит завтра до 12ти - на работе инет накрылся.

**Comment by jknightguru** [comment]
Сделано. Предложения на паре.
