### ISSUE TITLE
Невозможно использовать оптимизации

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#25]
Т.к. классы оптимизаций не публичные. Сделать их таковыми нельзя т.к. IOptimizer не публичен...

 Нужно:
1. Либо выполнять оптимизации при построении трехадресного кода
2. Либо сделать их публичными

Прошу главного архитектора в студию

**Comment by almikh** [comment]
Выполнять оптимизации при построении нам не нужно. Если есть желание, можешь сделать их публичными, тут я полностью согласен.

PS
Все это сломалось после ввода GUI. Что в нем такого, для чего нам требуется публичность, которая раньше нафиг не нужна была? Можно вместо объявления публичными всех методов решить эту проблему - и это было бы правильнее.

**Comment by unrealprox** [comment]
Ну у GUI все-таки свое пространство имен. Именно поэтому, если мы вызываем оптимизации отдельно, то они должны быть публичными

**Comment by almikh** [comment]
С чего бы там быть другому пространству имен... делай общее, у нас проект ведь один. GUI - лишь его часть.

**Comment by unrealprox** [comment]
Треадресный код и все остальное добро находится в namespace SimpleLang
а GUI написаны в namespace GUI. Что не понятно?

**Comment by unrealprox** [comment]
В общем, я не до конца разобрался в ваших проделках-переделках. Поэтому, пусть автор интерфейса IOptimizer сам исправляет свои грешки.

**Comment by almikh** [comment]
Ну ок.

> Чего не понятно

Все понятно, поэтому и надо всего то поменять пространство имени  у ГУИ. Первый мой вопрос ("С чего бы там быть <..>") был риторическим.

**Comment by unrealprox** [comment]
По мне, так GUI - это отдельный проект, который дает визуальный доступ к нашей библиотеке SimpleLang. Поэтому то, что у него свое пространство имен для меня кажется вполне естественным.

**Comment by almikh** [comment]
Эта версия тоже имеет право на жизнь)

**Comment by almikh** [comment]
Решено в коммите 3e051f89df2747
