### ISSUE TITLE
Unique ID generator isn't idiot-safe.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#3]
Use static class or singleton pattern for it; we don't need multiple instances of it, doesn't matter who uses it.

**Comment by almikh** [comment]
Пожалуй, насчет "isn't idiot-safe" я соглашусь...

Кроме того, это не единственная проблема этого генератора - нужно еще обыграть случаи, когда возвращаемая переменная есть в коде (мало ли, кому взбредет в голову использовать переменную с именем `t1`) - т.е. по-хорошему нужно генерировать многосимвольные, действительно случайные последовательности, без разделения на префиксы, вне зависимости от того, для метки генерируется идентификатор, или для переменной (не пойму, это ли ты подразумевал последними словами, или нет)... И, желательно, такие, чтоб никому и в голову не пришло использовать такие переменные в коде)

Такой вид генератор имеет лишь потому, что на тот момент этого было достаточно для возможности реализации остального функционала.

Не хочешь этим заняться?)

**Comment by jknightguru** [comment]
Просто тебе же потом твой код переписывать :) Подумаю. Давай так. Я залью генератор, только эта хрень перестанет компилироваться, ибо в чужой код я не полезу. Сразу после моего коммита постарайся переделать. Ок?

В подробности кода не вдавался, имелось в виду, что, например, найдется народ, догадавшийся отправить пустую строку в префикс, если придется сгенерировать уникальную строку, или передаст одинаковый префикс(тот же t). Будет он не один - будет жопа, которую будет практически невозможно найти.

**Comment by almikh** [comment]
Окей, делай. Я потом все доделаю в остальном коде, ну и мб в генераторе что подправлю/добавлю, если понадобится...

**Comment by jknightguru** [comment]
Сделал, и даже в твой код залез чутка. В инфе коммита все написано. Пока не закрываю.

**Comment by almikh** [comment]
Норм, крою.
