### ISSUE TITLE
Кодировка

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#30]
![image](https://cloud.githubusercontent.com/assets/4621400/10977772/27b3803a-8404-11e5-8c5d-91399c37e08a.png)

**Comment by jknightguru** [comment]
Завтра справлюсь с кодировками.

**Comment by almikh** [comment]
Поэтому я и был против русского языка в GUI...

**Comment by jknightguru** [comment]
Сделано.
