### ISSUE TITLE
В последнем коммите снова были разные платформы в проектах.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#32]
Предлагаю ВСЕМ удалить то, что есть, и склонировать репозитарий заново. Во избежание всякой ереси, подобной этой. А лучше - следить за тем, что пушите. Ну серьезно...

**Comment by almikh** [comment]
У тебя в студии в качестве цели был выбран не x86. Вот и все. 
Рядом с выпадающим списком Debug есть другой выпадающий список. Так вот, у меня в нем стоит x86, и стоял x86. У тебя, судя по всему, стоит Any CPU.

**Comment by almikh** [comment]
См. #33
