### ISSUE TITLE
chekist131, негодяй!

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#33]
Вот кто нам конфигурации в проект подобавлял!!!

Выпороть!

**Comment by almikh** [comment]
jknightmmcs, залезь в sln, удали появившиеся конфигурации нафиг. Можно прямо в текстовом редакторе, посмотрев на историю изменений sln.

**Comment by jknightguru** [comment]
Assigned - выпороть? =3

**Comment by almikh** [comment]
Это если он рядом)

**Comment by jknightguru** [comment]
Конфигурации грохнул, выпорем завтра вместе.

Кстати, довольно большой коммит залит, посмотри, что думаешь. Выбор как таковой еще не реализован, просто две грамматики интегрированы в проект. Враппер написать осталось.
