### ISSUE TITLE
Определение грамматики вне зависимости от расширения

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#34]
Мне кажется, наличия в тексте `{`, `}` достаточно, чтобы отличить, является ли эта грамматика грамматикой в стиле `C`, или грамматикой в стиле `Pascal`.

**Comment by jknightguru** [comment]
Ну, можно так еще оба парсера натравливать на код, смотреть, что получится. Костылирование примерно одинакового уровня :) А в чем трабла создавать файлы определенного расширения?

**Comment by jknightguru** [comment]
Если посмотреть, то у каждого языка есть свое собственное расширение файла - и именно по нему в основном определяется подсветка синтаксиса, и прочие задачи, вплоть до компиляции. А txt - это, на самом деле, глупо.
