### ISSUE TITLE
Пофлудим.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#35]
Однако!
![default](https://cloud.githubusercontent.com/assets/14237754/11001472/60e8e8d6-84b8-11e5-8f78-5506e699cfe5.png)
То ощущение, когда главный архитектор смотрит на твой код, как кот на пидрилу. :)
![rzky8oaepr8](https://cloud.githubusercontent.com/assets/14237754/11001569/d3724ea6-84b8-11e5-9f39-96f8ed305fc4.jpg)

**Comment by almikh** [comment]
Откуда вообще столько строк? Я столько не писал)

**Comment by jknightguru** [comment]
Интересно, 12к строк в проекте-то есть?:-)

**Comment by almikh** [comment]
Это, похоже, символы.

**Comment by jknightguru** [comment]
Не, 12к символов - это смешно. Хотя... Хрен знает, залей тестовый коммит с одной строкой, и проверь :-)

**Comment by almikh** [comment]
Мне это не настолько интересно)
