### ISSUE TITLE
Задача распространения констант у Ultimate

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#37]
**Ultimate**, за вами задача распространения констант. 
Если чего-то не нравиться - пишите

**Comment by AndranikTukhikov** [comment]
![image](https://cloud.githubusercontent.com/assets/14253787/11147142/fe0248f8-8a24-11e5-8b08-c0638ba1e52a.png)

**Comment by BatMich** [comment]
У нас была задача протяжки констант внутри одного блока. Это не совсем одно и тоже

**Comment by almikh** [comment]
#64 - дубль

**Comment by almikh** [comment]
Как дела обстоят?

**Comment by BatMich** [comment]
Обнаружилось, что в наш обобщенный итерационный алгоритм очень проблематично впихнуть свой оператор сбора (отличный от объединения и пересечения)... Ищем пути решения

**Comment by almikh** [comment]
На паре напомните мне, решим эту проблему.

**Comment by BatMich** [comment]
Выложил, чтобы архитектор мог ознакомиться с идеей. Пока что пользоваться нельзя - требуется отладка. Займусь завтра, ибо уже утро.

**Comment by almikh** [comment]
Похоже на правду.
Я, правда, не понял, зачем замена бинарных выражений на константу на этом этапе - по-идее, это должно производиться уже после работы итерационного алгоритма. Но буду считать, что так устроен алгоритм - до поры, до времени.

Ну и отладить не мешало бы - вылетает там. Но вам это и так известно.

**Comment by BatMich** [comment]
Все работает.

**Comment by almikh** [comment]
Действительно. Молоток.
Теперь осталось прикрутить это в алгоритм (новый) - и дело в шляпе.

Думаю, тут вы справитесь и без моих пояснений.
Ну и желательно с этим не затягивать, все-таки

**Comment by BatMich** [comment]
Готово. Заодно была исправлена ошибка в алгоритме. Теперь корректно отрабатывает на новых тестах
