### ISSUE TITLE
Проверка In-Out, Def-Use

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#39]
Переписал все с использованием нового графа. Нужно проверит, не сломалось ли чего.
Тесты же существуют?)

**Comment by jknightguru** [comment]
Хорошо, затестим. Не горит? Английский делаю =3

**Comment by almikh** [comment]
Вообще не горит.

**Comment by jknightguru** [comment]
На In-Out тестов у меня нет - я в его создании участия не принимал.

**Comment by almikh** [comment]
Там в обоих случаях похожие конструкции. Достаточно убедиться, что я все правильно понял и правильные данные проверю хотя бы в одном.

**Comment by jknightguru** [comment]
Def-Use: все хорошо.
