### ISSUE TITLE
IOptimizer.Optimize() modification issue

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#4]
It should be allowed to pass a number of parameters to the method, because in future it might be required, and reworking it at later stages of development will be messy and dirty.

Suggestion:

```
public void Optimize(params Object[] values)
```

This way it's possible to not pass any parameters at all(the way it happens now), as well as pass as many as we want.

**Comment by unrealprox** [comment]
Da der Code ist wie folgt:

```
SomeOptimizationClass soc = new SomeOptimizationClass(codeGenerator.Code);
soc.Optimize();
```

Ich denke, dass diese Parameter an den Konstruktor übergeben werden:

```
SomeOptimizationClass soc = new SomeOptimizationClass(codeGenerator.Code, params);
soc.Optimize();
```

**Comment by almikh** [comment]
Тонко)

Я тоже думая, что параметры будут лишними...
Дополнительные параметры/настройки, для каких-либо алгоритмов, можно передавать в отдельных функциях с осмысленными именами - в качестве специфической особенности именно для конкретного алгоритма.

С другой стороны, при пакетном применении алгоритмов оптимизации может понадобиться однообразная форма передачи параметров - а конструктор таковой формой не является.

Считаю, стоит отложить этот вопрос до появления первого алгоритма, где это может понадобиться. Или хотя бы до момента написания класса для вышеупомянутого пакетного применения оптимизаций.

**Comment by almikh** [comment]
А то пока не понятно, как будет лучше...

**Comment by jknightguru** [comment]
Просто сейчас это нужно поменять в трех-четырех местах - там, где хоть какие-то алгоритмы оптимизации написаны. И изменение совершенно не меняет форму вызова - там, как и раньше, можно совсем ничего не передавать. Соответственно, хуже не делает точно.

Делать это в конструкторах - маразм, ибо перед оптимизацией может стоять серьезный анализ, и проводить его каждый раз при отработке какого-то конкретного действия - глупость и трата ресурсов.

**Comment by jknightguru** [comment]
Немцы, лесом.

**Comment by almikh** [comment]
Считаю, вопрос закрыт.
