### ISSUE TITLE
Лишние файлы в проекте.

### ISSUE THREAD

**Issue by JKnightGURU** [mmcsIT2015/OptimizedCompilersProject#40]
Условились же, что генерируем сами из скриптов, по существующим грамматикам. У меня тут пулл обвалился из-за этого. Нет, ну понимаю, фиксится просто, но зачем?

Файлы:
 Common/SimpleLex_C.cs
 Common/SimpleLex_Pascal.cs
 Common/SimpleYaccC.cs
 Common/SimpleYaccPascal.cs

**Comment by kazanfar** [comment]
Да, виноват, извините

**Comment by almikh** [comment]
Ходил бы чаще на пары, знал бы, что мы условились зафиксировать эти файлы в репозитории и ими пользоваться) Все равно грамматики преимущественно меняться не будут.

Вот когда грамматика обновится - генерируем у себя файлы, убеждаемся в корректной сборке и заливаем.
