### ISSUE TITLE
Поместить файлы, связанные с лексерами/парсерами, в отдельный каталог

### ISSUE THREAD

**Issue by julbinb** [mmcsIT2015/OptimizedCompilersProject#41]
Очень много лишних файлов на верхнем уровне проекта. Лексеры/парсеры можно поместить в подкаталог. Это просто удобно.

**Comment by almikh** [comment]
Полностью согласен.Займется `vladpyslaru`.

**Comment by jknightguru** [comment]
Гг. Не занялся =3
