### ISSUE TITLE
Добавить интерфейс для передаточной функции

### ISSUE THREAD

**Issue by julbinb** [mmcsIT2015/OptimizedCompilersProject#42]
Класс `TransferFunction<T>` нормальный, но это только частный случай передаточной функции. В задаче распространения констант это будет нечто совсем другое, никаких `gen`/`kill` там нет.

Пока не написали ещё много кода, добавьте интерфейс или абстрактный класс для передаточной функции, в _ограничениях итерационного алгоритма_ нужно указывать _именно его_, а не класс передаточной функции для множеств.

**Comment by almikh** [comment]
При такой аргументации это имеет смысл, согласен.
