### ISSUE TITLE
Для FileLoader: научиться использовать System.IO.Path

### ISSUE THREAD

**Issue by julbinb** [mmcsIT2015/OptimizedCompilersProject#43]
Небольшой комментарий: для работы с файлами, каталогами именами есть стандартные методы. Например, `System.IO.Path` содержит кучу полезных методов для работы с именем файла, в том числе `GetExtension`, который _не_ используется в [FileLoader.cs | GetGrammarType](https://github.com/mmcsIT2015/OptimizedCompilersProject/blob/master/Common/FileLoader.cs)

**Comment by almikh** [comment]
chekist131, займись.

**Comment by jknightguru** [comment]
Я сделал - мой же код.
