### ISSUE TITLE
Использовать switch для перечислимого типа

### ISSUE THREAD

**Issue by julbinb** [mmcsIT2015/OptimizedCompilersProject#44]
Общечеловеческая рекомендация. Если есть значение перечислимого типа, то лучше писать `switch`, а не серию `if ... else if` для проверки этого значения. При использовании `switch` компилятор проверяет, что вы ничего не забыли (если, конечно, не написать `default`).

**Comment by almikh** [comment]
Я лишь смутно догадываюсь, кто такой `Park16`, но он просмотрит код и где это нужно все заменит) А то что-то нулевая активность у него получается) 

По-моему, это где-то в печати трехадресного кода подобный перебор есть - больше вроде нету.
Ну, а на нет - и суда нет. И тогда `Park16` повезло)

**Comment by unrealprox** [comment]
Park16 в моей команде и обычно все изменения производятся с моего логина.

**Comment by almikh** [comment]
Я так и думал) 

Еще я прикинул, по коду, и вроде у нас все теперь норм. А там, где все-таки есть перебор с помощью `if`, это в приципе можно обосновать. Так что делать ничего не нужно. Во всяком случае, пока)

**Comment by julbinb** [comment]
Ещё в FileLoader вроде бы было. Это просто замечание на заметку.

**Comment by jknightguru** [comment]
Сделал в FileLoader.
