### ISSUE TITLE
Планы

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#45]
Итак, хочу озвучить дальнейшие планы по поводу проекта (какими они видятся мне).

Следующая неделя (и, возможно, следующая за следующей) будет посвящена доделке всех открытых задач.

Далее разделимся следующим образом:
- Наша команда (`TrueDevelopers`) займется интеграцией наших оптимизаций в существующий компилятор;
- Команда `Source_Code` будет занята работой с IL-кодом. Тут хотелось бы от них еще услышать, как там обстоят дела с этим - можно ли наш трехадресный код в него преобразовать, есть ли какие-либо сложности или могут ли какие-нибудь сложности возникнуть в процессе и т.п. В общем, прошу их отписаться по этому поводу.
- Остальные будут заняты реализацией новых оптимизаций (а таковые, как я понял, будут) и доработкой существующих (если такая доработка потребуется). Также пусть каждая команда пишет документацию по своему модуля и некоторый набор тестов - как показала практика, без них некомфортно и сборка в любой момент может поломаться (по крайней мере в вопросе оптимизаций).

Короче, посоны, мы должны нагнуть все предыдущие проекты)

**Comment by unrealprox** [comment]
SourceCode:
мы в принципе уже наметили, что нужно сделать, но тут стоит еще следующий вопрос:
Будет ли грамматика дополнена? А то она слишком бедная. У нас есть вызов функций, а описания функций - нет. С типами тоже ничего не понятно. Нет никаких объявлений переменных. Мы, конечно, можем все сделать в терминах int32 и float32, но хотелось бы, чтобы были объявления.

**Comment by almikh** [comment]
С вызовом функций, я думаю, нужно что-то придумать. Это не кажется мне такой уж сложной задачей, можно поступать так, как все происходит в ассемблере: использовать `goto` и `ret`.

С объявлением переменных все немного сложнее... Сдается мне, там будет много возни. То же преобразование типов. Я предполагал обойти это следующим образом.

Сейчас у нас объявления как такового нет, у нас типа динамическая типизация. Но это не значит, что должно быть можно использовать неопределенную переменную, типа:

``` C++
a = 2;
b = c + a; // что за `c` такая?
```

Тут я предполагал анализировать код при (или после) генерации трехадресного кода и проверять, определены ли все переменные, которые используются в правой части выражений (т.е. прежде чем использовать переменную в вычислениях, нужно ей сперва что-нибудь присвоить). Если присутствуют ситуации, аналогичные указанной выше - ошибка "компиляции". 
Это кажется мне более простым решением.

Ну а при вычислениях уже пытаться приводить переменные к тому же float или int (строки как тип пока отложим (по кр. мере в вычислениях), если успеем - сделаем, но позже). Некий аналог динамической типизации, так сказать...

В общем, тут все упирается в сроки - успеем ли?

> Я там в вашем примере IL-кода видел, что все переменные в параметрах функции перечислены... Если у нас будет объявление переменной или его аналог, этого можно будет избежать?

Вы свои наметки по этому вопросу выложите сюда; мы посмотрим, насколько масштабные изменения/дополнения потребуются к основному проекту (вы их также можете обозначить). И если все более-менее приемлемо по срокам, кого-нибудь ими нагрузим, чтобы вас не отвлекать (если это возможно).

**Comment by unrealprox** [comment]
Мне главное, чтобы компилировался нормально "правильный" код (т.е. примеры, типа приведенного выше (где  c не определена) мне не сильно интересуют).

Вообще говоря, если мы хотим переводить все в IL-код, то типы нам нужны. 
По поводу функций, я думал переводить только некоторые, например, cout -> System.WriteLine. Т.к., все равно, смысла в вызове некоторой функции f() вообще никакого.

Пример перевода кода из нашей грамматики, в трехадресный код, а затем в IL-код можно посмотреть здесь: https://github.com/mmcsIT2015/OptimizedCompilersProject/blob/master/Teams/Source_Code/iltest/testing2.txt

Как можно заметить: типы нам нужны

**Comment by almikh** [comment]
> Мне главное, чтобы компилировался нормально "правильный" код

Поэтому и нужно браковать код неправильный, чтоб на этап трансляции в IL-код все было корректно.

В ближайшие дни создам задачи по составлении таблицы переменных, в которой будут храниться типы этих самых переменных. Ну и по поводу корректности использования переменных. Подробности позже.

По поводу функций... пожалуй, сделаем допустимыми лишь `write`, `writeln` на pascal, и `cout` (c/без `endl`) для С. Ну, может,еще для чтения функции введем, если понадобятся. Вы потом проверяйте через `if` эти функции и вызывайте соответствующие C#'вские, да и все. ЧТоб не заморачиваться. 

`chekist131`,  у меня для вашей команды задание: найди задачи, которые еще не сделаны, создай их здесь и назначь членам соответствующих команд. А то не разберешь, что уже сделано, а что нет...

**Comment by unrealprox** [comment]
> chekist131, у меня для вашей команды задание: найди задачи, которые еще не сделаны, создай их здесь и назначь членам соответствующих команд. А то не разберешь, что уже сделано, а что нет...

А потому что сразу надо было Issue делать для задач и назначать через assignee

**Comment by almikh** [comment]
> А потому что сразу надо было Issue делать для задач и назначать через assignee

С этим трудно спорить...
