### ISSUE TITLE
Непонятки с Gen-Kill 

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#46]
В лекциях, в описании метода достигающих определений, был пример вычисления множеств gen и kill. Так вот, наш код возвращает совершенно другой результат (по крайней мере для kill).

**Comment by jknightguru** [comment]
Посмотрю обязательно.

**Comment by jknightguru** [comment]
У нас же там было два варианта Gen-Kill: для одного блока(я делал), и Игорев - для множества блоков, я хз как он работает, ибо в принципе неясно, где оно там в конспекте описано, но он сказал, что нужно. Ты уверен, что тот смотрел?

**Comment by almikh** [comment]
А у Игоря не Def-Use случайно было?

В `TransferFuncFactory.cs` есть одна функция, и в ней с помощью Gen-Kill используются эти значения для блоков (я их собирал на основе именно твоей, если не ошибаюсь, реализации). Хотя, возможно, это было некорректно - т.е. из твоих gen-kill нельзя извлечь gen-kill для целых блоков.

Короче, ты больше знаешь. можно или нельзя.
