### ISSUE TITLE
Реализовать валидатор для трехадресного кода

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#47]
В классе `Gen3AddrCodeVisitor` появилась функция `VerifyCorrectnessOfProgram()`.

Она должна обойти все строки `mLine` класса `Gen3AddrCodeVisitor` и проверить, используется ли где-то в коде переменная, которой не присвоено значение. Что это значит?

Достаточно завести множество строк и для каждой переменной в левой части выражения (т.е. `Line.Operation`) заносить эту переменную в это множество. При этом сперва проверять правую часть выражения и смотреть: если какая-либо ~~переменная~~ из правой части еще не была определена (т.е. отсутствует в множестве определенных переменных) - то бросаем исключение (пример которого уже в функции  есть).

Т.е. у нас не должно быть ситуации, когда в коде используется какая-то переменная, которой не присвоено значение. Нужно для генерации IL-кода.

**Comment by kazanfar** [comment]
DoubleK не против.

**Comment by almikh** [comment]
Тогда вешаю на вас. Когда закончите - закройте эту задачу.

**Comment by kazanfar** [comment]
Сделано, вот только на унарных операциях (последний тест) не работает, т.к. функция GetDefUseInfo(); работает с бинарными операциями. Нужно ее доделать. Если что, я могу этим заняться, только не сегодня уже.

**Comment by almikh** [comment]
Пусть пока остается, там еще изменения планируются, после них поправишь.

**Comment by kazanfar** [comment]
Я тут кое-что подправил, скажите, кто будет смотреть, норм или нет. Желательно еще потестировать на нескольких тестах.

**Comment by almikh** [comment]
Пока неактуально...
