### ISSUE TITLE
Структурирование

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#5]
- Удалить личные папки, не нужны они.
- В общей папке поместить грамматики для C, Pascal, скрипты для их обработки.
- Доработать организацию тестирования.

**Comment by jknightguru** [comment]
Предлагаю ввести политику приоритета С-грамматики. Т.е, если кто-то накакал в файлах генерации дерева по входному файлу(любых), то он это перед коммитом вернет на место. Либо, не будет коммитить их вообще. Все-таки, у нас большинство С-грамматику реализуют, и права меньшинств будут сильно мешать большинству.

**Comment by almikh** [comment]
Я бы их в .gitignore добавил, генерируемые файлы эти.
