### ISSUE TITLE
Построение графа dom (Ultimate)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#53]

**Comment by valyaevanton** [comment]
Я предлагаю для хранения дерева использовать Dictionary < Block, IEnumerable< Block > > чтобы удобней было

**Comment by almikh** [comment]
Чет у Ultimate многовато задач... Пока внимание стоит сосредоточить на тех, на которых нет тэга `позже`

**Comment by AndranikTukhikov** [comment]
Сделано.
