### ISSUE TITLE
Определить, является ли граф приводимым (DoubleK)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#58]

**Comment by kazanfar** [comment]
Для этой задачи нужен список отступающих ребер CFG

**Comment by almikh** [comment]
Потрясите того, кто этим занимается.

**Comment by kazanfar** [comment]
И кстати, вопрос : нужно ли обратные и отступающие ребра искать в остовных деревьях? И следующий вопрос, если не нужно, то зачем их реализовывать?

**Comment by kazanfar** [comment]
Сделал, но мне кажется, что не совсем правильно работает. Я залил тест с примером неприводимого графа, который мы рассматривали на лекции, так вот выводит, что граф приводимый.

**Comment by valyaevanton** [comment]
1. Зря ты засунул всё в SpanningTree. Сделай свой отдельный класс, который бы принимал SpanningTree и прочее как параметры (в конструкторе например). Это мне не нравиться т.к. spanningTree писал я.
2. Там где у тебя Blocks, вставь вместо него шаблон и попробуй потестировать свой код с int вместо block. Для этого нужно будет взять класс AllCyclesTesting.TestGraph и заполнить его руками, blocks - это просто массив из intов (блоки должны быть от 1 до n последовательно). Потом всё это подать на вход spanningTree и получаем остовное дерево с типом int (это просто совет)

**Comment by kazanfar** [comment]
Ок

**Comment by kazanfar** [comment]
Несколько тестов написал, но все они проваливаются. Хотя второй тест должен был пройти.

**Comment by valyaevanton** [comment]
Добавил тестовое остовное дерево, лежит там же где и тестовый граф. Можешь попробовать заполнить его на прямую. А дальше: дебажить и ещё раз дебажить)

**Comment by kazanfar** [comment]
Запустил на всех тестах, пишет везде, что граф приводимый. Вот скрин
![graphcompilers](https://cloud.githubusercontent.com/assets/14237970/11920022/ff9cf782-a773-11e5-8220-67a601fd71cc.jpg)
Так и должно быть, правда на неприводимых графах не проверял.

**Comment by almikh** [comment]
Тогда будем считать, что задание сделано. Обязательно в ближайшее время в документацию добавить, как этим пользоваться.

**Comment by kazanfar** [comment]
Правда я еще потестил на неприводимом графе, пишет, что приводимый. Но, возможно, косяк не в алгоритме определения приводимости, а в других классах. А их проверять не очень охота.

**Comment by almikh** [comment]
> потестил на неприводимом графе, пишет, что приводимый

А это уже косяк. Надо искать, че.

> возможно, косяк не в алгоритме определения приводимости, а в других классах

А возможно, именно у вас. Тут только проверять и проверять, больше никак. Время еще есть.

**Comment by jknightguru** [comment]
Закрыто, т.к. проект сдан.
