### ISSUE TITLE
Генерация IL-кода (Source_Code)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#60]

**Comment by almikh** [comment]
Ну что, увидим мы на этой паре что-нибудь уже? Или нет? Как там дела обстоят? 
Хотелось бы хоть простые инструкции (сложение, вычитание и т.п.) уже наблюдать...

**Comment by unrealprox** [comment]
Постараюсь к пт доделать
