### ISSUE TITLE
Оптимизации, связанные с анализом активных переменных (DoubleK)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#67]

**Comment by almikh** [comment]
Пример.

Используете DataFlowAnalysis.GetActiveVariables(code)

> В Out[block] у вас будут живые переменные при выходе из блока.

Ну а теперь как обычно идете снизу вверх по блоку и смотрите на переменные.
Если вам встретилось, к примеру, `x = ...`, и при этом `x` в `Out[block]` нет - т.е. ее нет в списке живых переменных, т.е. она мертвая - то эту строку можно удалить.

**Comment by kazanfar** [comment]
Я понял. Вчера просто скачал проект, так там он некорректно работал. Сейчас не смотрел

**Comment by kazanfar** [comment]
Типа сделано. Только есть подозрение, что алгоритм не работает, потому что Out'ы всегда пустые, и он работает как обычный DCE алгоритм (т.е. рассматривает каждый блок независимо)

**Comment by almikh** [comment]
Ну, это уже другой вопрос. Завтра гляну.

**Comment by kazanfar** [comment]
Такой вопрос возник : нужно в каждом блоке проверять переменные на живучесть, как это было в DCE алгоритме, или же достаточно проверять принадлежность переменных в левой части строкам из OUT и только?

**Comment by almikh** [comment]
Короче, вот новая вводная.

Я переписал ActiveVarsOptimization - изначально не нужно было вносить изменения непосредственно в код алгоритма DCE. Несмотря на то, что сейчас все больше похоже на правду, в некоторых ситуациях алгоритм не срабатывает как положено, и удаляет лишние конструкции (т.е. которые удалены быть не должны).

Я подправил код `test-dce1.cn` - нужно отталкиваться от него. К примеру, в первом блоке удаляется одна из переменных, которая используется в правой части присваивания одной из переменных третьего блока. Можно запустить без оптимизации и с оптимизацией, посмотреть разницу - и все станет понятно. 

> Удалением некоторых переменных в последнем блоке можно пренебречь - это ж типа конец программы, переменные не используются, вот они и удаляются вообще). Но косяк выше - недопустим.

Нужно взять, и на бумажке проделать все операции итерационного алгоритма для этого примера. Потом результаты желательно выложить сюда (прямо фотографии этой ручной работы) - чтобы я увидел, есть ли где косяк, или нет.

Разбиение на блоки понятно как получить, множества def-use для этих блоков можно извлечь из функции TransferFuncsForActiveVariables, в частности, в строках                 

```
var def = new HashSet<String>(info.Def);
var use = new HashSet<String>(info.Use);
```

Это как раз def-use для определенного блока.

Больше задач пока не даю, потому что с этой нужно разобраться. Желательно, проделать это все в ближайшие дни.

**Comment by kazanfar** [comment]
Ок

**Comment by almikh** [comment]
Нашел косяк, он был не в итерационном алгоритме, а в генерации передаточных функций. 

> в вручную решенном примере тоже были ошибки, но я их заметил, так что все-таки он мне помог

Теперь надо проверить работу этого алгоритма, снова. Главное - смотреть, чтобы он ничего лишнего не удалил. Пусть не все удаляет, но если есть отличия от обычного DCE, и ничего лишнего не удалено, то все норм. В `dce-1` вроде все норм. После проверки отпишитесь сюда.
