### ISSUE TITLE
Оптимизации, связанные с анализом доступных выражений

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#68]

**Comment by vladpy8** [comment]
Доступные выражения можно смотреть. Но предупреждаю, пока не особо тщательно тестировал. Только на кейсах:
test-exprgenkill-1.cn
...
test-exprgenkill-5.cn

**Comment by almikh** [comment]
Задачу беру на себя, если работу над ней еще не начали. Начали, или нет?

**Comment by almikh** [comment]
Оптимизации прикрутил.
Класс является наследником ConnomSubexpressionOptimization. Дополнение заключается в инициализации начального словаря выражений для блока - теперь он не пусто, а заполнен данными из InOut<Line.Expr>.
