### ISSUE TITLE
Набор тестов для анализа достигающих определений (Ultimate)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#69]

**Comment by almikh** [comment]
Код  по этому вопросу вроде уже написан: `Main.cs -> TestIterativeAlgo()`. На входе - трехадресный код, на выходе - значения `IN` и `OUT` для каждого блока. Хз, что там тестировать - на примере, приведенном на лекции (по вычислению с помощью итерационного алгоритма достигающих определений на входах/выходах блоков) все сработало правильно.

**Comment by AndranikTukhikov** [comment]
Проверю вручную на нескольких примерах.

**Comment by AndranikTukhikov** [comment]
При запуске примера "test-3.cn" выдалась неприятность вида:
"Unexpected error: The given key was not present in the dictionary."
Причем исключение выкидывается отсюда:
![image](https://cloud.githubusercontent.com/assets/14253787/11425775/671742f6-9468-11e5-89c8-81312a4c2eb7.png)

**Comment by AndranikTukhikov** [comment]
При запуске примера "test-1.cn" все хорошо, но возникает другая фигня при запуске функции TestIterativeAlgo.
Исключение выкидывается тут:
![image](https://cloud.githubusercontent.com/assets/14253787/11426561/0990c5de-946e-11e5-94f6-bfeff7a5f99d.png)

**Comment by BatMich** [comment]
Это уже давно сделано для этого алгоритма (test-1.cn - test-10.cn).

**Comment by almikh** [comment]
Занесите тогда эти тесты в отдельную папку. Ну, или название более информативное дайте... хотя лучше - в папку. А косяки я посмотрю.

**Comment by almikh** [comment]
`test-3.cn`, а также все существующие тесты нужно переписать. Теперь у нас для всех переменных, которые используются в коде, нужны объявления.

**Comment by almikh** [comment]
Насчет TestIterativeAlgo: в коде вычисления gen/Kill была ошибка (опечатка?)
