### ISSUE TITLE
Реализовать в С-грамматике вызов функций

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#7]
С переменным количеством параметров, само собой.
Есть желающие?

**Comment by jknightguru** [comment]
Только вызов? Или описание тоже?

**Comment by jknightguru** [comment]
На самом деле, пять минут дела, если речь о вызове.

**Comment by almikh** [comment]
Пока достаточно класса и конструкции в .y
Хотя генерация кода тоже не так уж и сложна

**Comment by jknightguru** [comment]
Сделано! Visit() бросает NotImplementedException.

**Comment by almikh** [comment]
Написал генерацию.
