### ISSUE TITLE
Общий рефакторинг кода (TrueDevelopers)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#71]

**Comment by almikh** [comment]
А эта задача откуда взялась?)

**Comment by valyaevanton** [comment]
Я сам её придумал)

**Comment by kazanfar** [comment]
Леха, проверь на тесте
begin
    a := 4.5;
    b := 3;
    c := f(a + b);
    writeln(a, b, c)
end.
Ошибка называется Unexpected error: Данный ключ отсутствует в словаре

**Comment by almikh** [comment]
У нас же теперь объявления есть) Точнее - должны быть.
Типа 

```
float a:=4.5;
int b := 3
```

и т.п. Это, конечно, не для стиля паскаля, и по-хорошему в вашем случае это стоило бы переписать иначе (каюсь - мой косяк, сразу не подумал), но все же попробуй обозначить типы и снова запустить.

Вообще, это больше задача по валидации кода, но я пока не смог ее нормально переформулировать.

**Comment by kazanfar** [comment]
Не, не работает даже с объявлениями( А где переписывать надо, в грамматике или в самом коде?

**Comment by kazanfar** [comment]
И тест, который я залил, работает без объявлений)
