### ISSUE TITLE
Всем нужно отписаться в issues о выполняемых/выполненых заданиях

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#72]
По последним выданным на лекциях заданиям были созданы issue. Каждой команде в нужно отписаться в соответствующих темах выполнили ли они задания или почему не выполнили. Задание считается выполненным только после одобрения Лёхой

**Comment by almikh** [comment]
Всех плевать на это сообщение)

**Comment by valyaevanton** [comment]
Как скажешь, ты же тут главный
