### ISSUE TITLE
Удаление "мертвого" кода некорректно работает на унарных операциях

### ISSUE THREAD

**Issue by kazanfar** [mmcsIT2015/OptimizedCompilersProject#73]
Конечно, если постараться, можно понять что к чему, что удалилось, а что нет (см. тест test-dce3.cn). Но хотелось бы, чтобы лишние выражения с унарной операцией нормально удалялись. Подозреваю, что проблема в генерации переменных.

**Comment by almikh** [comment]
Вообще говоря, этим должны были заниматься оптимизации. Проблема в том, что все наши реализованные оптимизации работают в пределах базового блока, и поэтому не могут корректно распознать, можно ли удалить переменную, или нет.

PS.
Я то генерацию немного изменил, и теперь все должно быть нормально (временных переменных больше не создается, когда их можно избежать), но я по-прежнему считаю, что это - задача оптимизаций.

Проверь сейчас, если все нормально - закрывай задачу.
