### ISSUE TITLE
В грамматику Pascal добавить поддержку чисел с плавающей запятой.

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#75]
По-сути - требуется воспроизвести в паскалевской грамматике изменения из грамматики С, которые есть в коммите ceaf37aa5

**Comment by kazanfar** [comment]
Ок, сделаем.

**Comment by almikh** [comment]
Ну, есть успехи?

**Comment by kazanfar** [comment]
При тестировании падает на функции CompleteTableOfNames(), а именно при попытке обработать строку с вызовом функции

**Comment by almikh** [comment]
Падает и на cn, и на pasn-файлах? Или только на ваших?
Было бы неплохо, если бы ты сам разобрался, но если неохота - просто закомментируй вызов, и залей так.

**Comment by kazanfar** [comment]
На .cn не проверял, проверял на .pasn. Я уже залил, с одним рабочим тестом, просто бывают ситуации, когда выкидывает исключение.

**Comment by kazanfar** [comment]
Пока я только понял, что программа в некоторых случаях интерпретирует вызов функции как выражение с бинарной операцией.

**Comment by almikh** [comment]
Напиши сюда (https://github.com/mmcsIT2015/OptimizedCompilersProject/issues/71), что за исключение  и как повторить ошибку, и можешь закрывать задачу.
