### ISSUE TITLE
Def-Use: проверка корректности

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#78]
Переписал эту ф-ю, были косяки. Нужно проверить, не упустил ли я чего. Кто этим занимался?

**Comment by TheVigor** [comment]
Я этим занимался. Тогда у нас еще унарного оператора не было, когда эту штуку писал. Вообщем, тогда это дело потестирую и добавлю тесты для анализа активных переменных.
