### ISSUE TITLE
добавьте в грамматику конструкцию cout << expr << endl;

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#83]
Это в принципе не сложно. Достаточно пару строк в грамматике и флаг в coutNode. Но зато потом пригодится для написания "нужных" программ.

Пс. Можно сразу и cin>>id; добавить

**Comment by almikh** [comment]
Я что-то считал, что первое уже есть...
Согласен, эти изменения нужны.

**Comment by almikh** [comment]
`jknightmmcs` у нас уже собаку съел на подобных изменениях, он и займется.

**Comment by jknightguru** [comment]
Сделаю.

**Comment by almikh** [comment]
Как дела обстоят? А то тут новая задачка вырисовывается, пусть не такая и большая.
