### ISSUE TITLE
Документация (Альфа)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#86]

**Comment by almikh** [comment]
Ты бы папку сюда залил, с документацией (точнее, ее материалами), и пусть бы все потихоньку заполняли ее.

**Comment by almikh** [comment]
Как раз вместе бы и определили детали, о которых стоит упомянуть, а какие можно опустить.

**Comment by almikh** [comment]
Ну что, идет процесс? Неплохо бы хотя-бы заготовку сделать к следующей паре. Хотя бы папку создать)

**Comment by valyaevanton** [comment]
К слудющей паре уже что-нибудь придумаю по этому поводу

**Comment by almikh** [comment]
К следующей паре желательно уже все сделать. Не текст, само собой, но структуру, в которую этот текст можно вставлять. Разбивать  то ли по командам, то ли по сходству задач... Потом для сборки этого всего в один файл я скрипт напишу, если потребуется. Но тянуть, мне кажется, не стоит... по-сути, 2 пары осталось,все-таки.

**Comment by valyaevanton** [comment]
Добавил структуру проекта виде папок и прогу которая их собирает. Она заголовки, текст и т.п., увидишь в результирующем файле. Вот она https://github.com/chekist131/DocumentationAssembler. Структуру можешь менять, а насчёт содержимого мы ещё думаем.
