### ISSUE TITLE
Определение вложенности естественных циклов (DoubleK)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#87]

**Comment by almikh** [comment]
Типа надо найти исполнителя?

**Comment by valyaevanton** [comment]
Ага

**Comment by gggcode** [comment]
Лес рук, да?)

**Comment by almikh** [comment]
А запилите вы и эту. Как раз же определение этих циклов вы делали, так что вам не сложно должно быть.

**Comment by valyaevanton** [comment]
Теперь задача у DoubleK

**Comment by valyaevanton** [comment]
Можете использовать уже готовые тесты.
Для этого нужно прописать определение вложенности циклов и вывод в AllCyclesTesting.AllCyclesTestExampleAbstract.TestCyclesHierarchy() .
Вызывать из main с помощью AllCyclesTesting.TestCyclesHierarchy();
Можно добавить свои примеры по образцу, наследуя их от AllCyclesTestExampleAbstract, и вызывать их в AllCyclesTesting.TestCyclesHierarchy() .
Кроме этих двух методов и добавления своих классов примеров ничего ни в AllCycles, ни в AllCyclesTesting менять не надо.
Удачи

**Comment by valyaevanton** [comment]
1.Тебе стоит вынести свой алгоритм из метода TestCyclesHierarchy() в отдельный класс, и просто вызывать его здесь.

2.Вывод я написал неправильный т.к. писал его просто как пример вывода. По идее оно должно выводиться рекурсивно (напиши ещё одну функцию для этого). 

3.Для рекурсивного вывода нужно ещё знать корень, а он может быть и не одной вершиной. Пусть корнем будет List< Cycle < T > >  root, который тоже возвращает твой алгоритм.

4.Ну и конечно, если тестируешь нужен шаблон. Т.к. тестируем мы типом int, а использовать будем с типом Block (может быть придется дописать в классе where T : IComparable< T > и сравнивать через t1.ToCompare(t2) == 0 )

**Comment by kazanfar** [comment]
А сейчас?)

**Comment by valyaevanton** [comment]
Помести класс в отдельный файл. 

А так не знаю, не смотрел)

**Comment by valyaevanton** [comment]
Сделал, больше разговоров было

**Comment by kazanfar** [comment]
Ну хорошо, раз так
