### ISSUE TITLE
Подправить генератор имен

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#9]
Для отладки добавить возможность генерировать удобочитаемые имена.
Удалять все жалко, добавлю доп. опцию генератора.

**Comment by jknightguru** [comment]
```
#if DEBUG
code-debug
#else
code-release
#endif
```

**Comment by jknightguru** [comment]
По-моему, максимально хороший вариант в данном случае.

**Comment by almikh** [comment]
Вообще говоря, это обычно и используется. Но боюсь, мы просто-напросто не дойдем до варианта с `#else`, и вечно будем в первой ветке (неужели у кого-то есть подобные иллюзии?))

Т.к. проблема с встречаемостью временных переменных в коде решена добавлением символа, который пользователь ввести не может (`@`), то мое прежнее предложение о генерации имен (с использованием набора символов и т.п.) теряет актуальность... 

Да и народ недоволен, хочет удобочитаемых имен)
Так что я склоняюсь к варианту вообще удалить прежнюю генерацию, оставив идею Singleton'а и мои последние исправления. Чтобы не засорять код.

Какие еще есть мнения?
