### ISSUE TITLE
Выделение областей (SourceCode)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#90]

**Comment by almikh** [comment]
Есть успехи?

**Comment by unrealprox** [comment]
Сделал. Нужно проверять работу.

Использование:

Region first = Region.RegionsDetermination(code);

Возвращает ссылку на первую область.
У всех областей всех типов есть свойства NextRegions и PrevRegions

У областей типа SimpleRegions, есть свойство Block (любой блок - это область)
У областей типа CycleBodyRegions, есть свойства Head и OutsEdges
У областей типа CycleRegions есть свойства CycleBody и ReversedRegions

Пример, как пользоваться смотри в Region.Test(code).

**Comment by almikh** [comment]
Т.е. последняя область - это самый крупный регион? Исходя из того, что `Region.RegionsDetermination(code)` возвращает ссылку на первую область.

**Comment by almikh** [comment]
Также, я правильно понимаю, что ваш алгоритм строит `восходящую последовательность областей`? Хотя это, наверное, по сути и есть предыдущий вопрос...

**Comment by unrealprox** [comment]
Алгоритм строит граф областей
![image](https://cloud.githubusercontent.com/assets/4621400/11938060/fd9d706e-a828-11e5-850c-a46f5654d813.png)

На данном примере ты получишь список областей из 4ех областей (и получишь ссылку на 1ую)
При этом т.к. 2 область - область цикла, то в нем будет свой подграф областей, а внутри него еще 1 есть.

ПС. Смотри пример Region.Test(code) и будет все понятно.
ПС2. Строить список восходящих областей тебе нужно будет строить вручную.

**Comment by almikh** [comment]
Будь добр, пронумеруй на этом примере области в том порядке, в котором они будут доступны из вашего класса.

**Comment by almikh** [comment]
Используя ваши структуры регионов, можно ли как-то создать макрорегион (т.е. регион, включающий весь граф)?

**Comment by unrealprox** [comment]
Зачем тебе это?

**Comment by almikh** [comment]
Потому-что последняя область в восходящей последовательности областей - весь граф (или все области, хз как правильнее сказать).

**Comment by unrealprox** [comment]
Создай наследника от Region с полем SimpleRegion и будет тебе макрорегион
