### ISSUE TITLE
Реализация алгоритма на основе областей (???)

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#91]

**Comment by unrealprox** [comment]
> Есть успехи?

**Comment by almikh** [comment]
Сегодня вечером отчитаюсь.

**Comment by almikh** [comment]
В 2e59bc6 я написал генерацию восходящей последовательности регионов.Пользоваться для этого существующим кодом, который создает регионы, чертовски неудобно.

Поэтому в итоге получился такой говнокод, что я его боюсь.
Кроме того, я не уверен, что **внутри** регионов (за исключением простых регионов) внутренности расположены в топологическом порядке.

**Comment by unrealprox** [comment]
> Пользоваться для этого существующим кодом, который создает регионы, чертовски неудобно.

Ничего не знаю. Я считаю, что задание по выделению регионов было добросовестно выполнено. И мы, на сколько я помню, спрашивали, в каком виде хотелось бы тебе получать регионы. А то, что ты решил ждать до последнего - твои проблемы. Не надо тут говорить про "чертовскую неудобность."

> Кроме того, я не уверен, что внутри регионов (за исключением простых регионов) внутренности расположены в топологическом порядке.

А в каком порядке? внутренности располагаются согласно графу CFG.

**Comment by unrealprox** [comment]
> Поэтому в итоге получился такой говнокод, что я его боюсь.

Если не нравится "такой гавнокод" можешь воспользоваться моим (написал специально для тебя на коленках только что, обошлось без "гавнокода")

смотри Region.AscendingSequenceOfRegions()

Тестовый пример Region.TestASoR()

Последовательность получается не в точности как у тебя, но условию "восходимости" - каждая последующая область либо не пересекается с пред либо объемлет часть предыдущих - удовлетворяет

**Comment by almikh** [comment]
> Я считаю, что задание по выделению регионов было добросовестно выполнено.

Так я обратного и не утверждал. 'Неудобно пользоваться' и 'не выполнено' - разные вещи.

> А то, что ты решил ждать до последнего

А чего я ждал до последнего? Как только вы написали алгоритм выделения областей, я и принялся за основной. Так что обвинений не нужно.

> Если не нравится "такой гавнокод"

Ну, если он мне не нравится, это не значит, что я бы его не использовал.

**Comment by almikh** [comment]
В любом случае, алгоритм этот мы (в моем лице) делать не будем. Сегодня я весь день просидел еще с одним серьезным косяком, а завтра мне еще и документацию дописывать придется.
