### ISSUE TITLE
Определение тела if для трехадресного кода

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#92]
Собственно, нужно написать ф-ю, которая будет определять, какие строки являются телом then, а какие - телом else (если таковое имеется). Ну и какие отвечают за condition (тут придется проследить цепочку временных переменных).

if у нас генерируется однотипным образом, и достаточно воспользоваться этими правилами генерации для, так сказать, "реверсинжиринга".

Жду желающих. Поверьте, лучше вам делать это задание, чем последнее, с областями...

**Comment by vladpy8** [comment]
я плохо себе представляю, что такое IL код, но разве там нет goto?

**Comment by almikh** [comment]
Это не имеет никакого отношения к IL-коду.

У нас есть такая структура:

``` cs
    public class if_node : statement
    {
        protected expression _condition;
        protected statement _else_body;
        protected statement _then_body;

        public if_node();
        public if_node(expression _condition, statement _then_body);
```

для нее нужны список строк для тела then и  else. В принципе, без этого можно обойтись - но хотелось бы сделать все по-человечески.

**Comment by vladpy8** [comment]
а зачем эта структура?

**Comment by almikh** [comment]
Это элемент синтаксического дерева из PascalABC

**Comment by vladpy8** [comment]
а без нее не получится? там же есть goto?

**Comment by almikh** [comment]
> В принципе, без этого можно обойтись - но хотелось бы сделать все по-человечески.

^

**Comment by vladpy8** [comment]
По-человечески - это значит с мучениями/костылями/возможными ошибками?
По-моему,  это будет лишей тратой времени

**Comment by almikh** [comment]
По-человечески - это значит так, как было задумано в этом дереве. А не  через одно место...

**Comment by almikh** [comment]
Ну че там?

**Comment by oltr** [comment]
Занимаюсь, планирую завтра закончить.

**Comment by oltr** [comment]
Закрыто по указанию главного архитектора.
