### ISSUE TITLE
Сворачивание выражений из трехадресного кода в нормальный вид

### ISSUE THREAD

**Issue by almikh** [mmcsIT2015/OptimizedCompilersProject#93]
Пример:

``` cs
@t1 = 2 + 3
a = 2*@t1
```

Из этого можно получить выражение для а:

``` cs
a = 2 * (2+3)
```

Нужно реализовать этот механизм. Можно сразу с паскалевским деревом (проект в решении - PascalABC), можно во что-то абстрактное, вплоть до обратной польской записи... Нужен код, это реализующий - результат не важен, я буду использовать лишь код алгоритма.

**Comment by TheVigor** [comment]
Возьмусь за эту задачу.
