### ISSUE TITLE
Хьюстон, у нас проблема

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#94]
![image](https://cloud.githubusercontent.com/assets/4621400/11712792/56983150-9f40-11e5-9b63-06fc66d5116e.png)

**Comment by almikh** [comment]
Косяк в грамматике(.lex и .y файлах). Нужно найти, что мы упустили.

**Comment by jknightguru** [comment]
С работы вернусь - сразу посмотрю.

**Comment by jknightguru** [comment]
Он тут .txt файлы тянет, а такое в принципе работать не должно. Обновите вашу копию проекта, товарищи! А еще лучше - не занимайтесь фекализацией проекта и используйте бранчи вместо этих недокопий.

**Comment by jknightguru** [comment]
А еще - можно мне представить, каким образом себя должен генератор кода вести в случае { float t = 5; } ? Я просто не в курсе, что там сделали с объявлениями,

**Comment by jknightguru** [comment]
Увидел, в чем проблема.

**Comment by almikh** [comment]
Тип не передается...

**Comment by jknightguru** [comment]
Сделано! В свои подпроекты переносим сами.
