### ISSUE TITLE
Как это работает, вообще?!

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#95]
![67](https://cloud.githubusercontent.com/assets/4621400/11714972/2ba3d8b4-9f4f-11e5-8ebc-12ec0c9a86a8.png)
![68](https://cloud.githubusercontent.com/assets/4621400/11714973/2c4d188e-9f4f-11e5-8e4e-82b0d39f55d2.png)

**Comment by unrealprox** [comment]
![image](https://cloud.githubusercontent.com/assets/4621400/11715041/b772e18c-9f4f-11e5-93be-53cba8873242.png)
Кто это писал?!

**Comment by unrealprox** [comment]
Исправил

**Comment by almikh** [comment]
Писал я. Действительно, опечатался.
