### ISSUE TITLE
Кто же такой патриот?

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#96]
Спасибо тому, кто реализовывал класс Line.ConditionalJump, у которого первая буква РУССКАЯ! Вы НАСТОЯЩИЕ патриот!

**Comment by almikh** [comment]
А я то думаю, чего это у меня C# по нажатию на С не подтягивает мне этот ConditionalJump в подсказке...

А как это обнаружилось, если не секрет?

**Comment by unrealprox** [comment]
Ну также, через автодополнение + смекалка

**Comment by almikh** [comment]
Ну круто; молоток, что нашел. Не критично, конечно, было, но действительно неприемлемо.
