### ISSUE TITLE
IL-код

### ISSUE THREAD

**Issue by unrealprox** [mmcsIT2015/OptimizedCompilersProject#97]
Сделали первую версию генерации IL-кода

Было бы неплохо добавить в GUI какую-то графическую визуализацию

Пример использования:
ILCodeGeneration.GenILCode(code);

Результат работы можно посмотреть на тесте:
./Common/tests/test-ilgen.cn

Как скомпилировать программу можно посмотреть здесь:
./Teams/Source_Code/iltest/compile.cmd

**Comment by almikh** [comment]
GUI прикрутим. На паре определимся, кто эти займется.
