### ISSUE TITLE
Всем нужно написать документацию по их заданиям

### ISSUE THREAD

**Issue by valyaevanton** [mmcsIT2015/OptimizedCompilersProject#98]
Всё для этого необходимое находится в папке Documentation в корне проекта

**Comment by almikh** [comment]
А почему там все файлы - txt?

**Comment by valyaevanton** [comment]
А какая разница?...

**Comment by unrealprox** [comment]
А можно сгенерированный файл текущей документации (PDF) закоммитить? Хотелось бы глянуть.

ПС. Возможно был кем-то добавлен в .gitignore

**Comment by valyaevanton** [comment]
Не понимаю зачем оно тебе. Тем не менее можешь перевести docx в pdf прямо из word. Можешь ещё попробовать сделать это с помощью pandoc с установленным miktex, но так делать не советую

**Comment by unrealprox** [comment]
> Не понимаю зачем оно тебе. 

Хотелось бы глянуть.

> Тем не менее можешь перевести docx в pdf прямо из word. 

Если бы docx был бы (а его нет, т.к. он  в .gitignore), то я, наверное, бы и не просил закоммитить.

> Можешь ещё попробовать сделать это с помощью pandoc с установленным miktex, но так делать не советую

Я не хочу ничего устанавливать, поэтому и прошу.

**Comment by valyaevanton** [comment]
В gitignore документация добавлена специально, чтобы каждый установил себе pandoc, собрал docx со скриптом и посмотрел, как будет выглядеть его кусок и, если что, поправил
